src/Mpociot/VatCalculator/VatCalculatorServiceProvider.php

I noticed a small glitch when using the Controller class, which comes in play when using the frontend integration.
A VatCalculator instance is injected in the constructor of this class. But when the container resolves this class, it doesn't use the binding defined in the service provider (`registerVatCalculator()`), as this only binds the facade, not the main class. For the main class, the container will just use basic reflection, which is ok most of the times, but it means the $config parameter is not set.
This results in not having the config set in this controller, and ultimately the frontend integration ignoring your custom config (e.g. the business_country_code).
This PR makes sure the \Mpociot\VatCalculator\VatCalculator class is also bound.
Thank you for your feedback and/or …

Also bind the full class name in the service provider, not only the facade

---

src/Mpociot/VatCalculator/Traits/BillableWithinTheEU.php

In Laravel Cashier 6.0, the function to get tax rate is now ``taxPercentage()`` instead of ``getTaxPercent()``

Add taxPercentage() for Laravel Cashier 6.0

---

src/public/js/vat_calculator.js

Better detection of the dropDown (should be a `select` element with `data-vat="country"`)
If we already know the client country, we can use an hidden field and vat-calculator.js will work the same way.

Allow usage of an hidden country field

---

src/Mpociot/VatCalculator/VatCalculator.php
tests/VatCalculatorTest.php

Fixes #30, by returning the default rate after checking for post code exceptions.

Fix postal code exceptions causing VAT to be zero-rated.

---

src/Mpociot/VatCalculator/VatCalculator.php

Romania VAT updated its from 20 to 19% on January 1st 2017

Romania VAT updated its from 20 to 19% on January 1st 2017

---

src/controllers/Controller.php

Fixes #45 , by loading the (global) config in the constructor and create
a new instance that passes the config as argument.

Fix VAT Calculator JS returns zero tax for business country code

---

src/Mpociot/VatCalculator/VatCalculator.php
src/config/config.php
tests/VatCalculatorTest.php

these commits add possibility to catch soap exceptions (sometimes needed when you want to validate vatid manually using regex once VIES is down)

Exceptions option

---

src/Mpociot/VatCalculator/VatCalculator.php

Changed `[2,]` (=match either digit 2 or comma) to `{2,}` (=match 2 or more times)

Correct regex for Madeira/Azores postcodes

---

src/controllers/Controller.php

When using this package inside Laravel 5.4, command **php artisan route:list** is broke because config repository is not correctly being resolved.
Instead, the repository can be type hinted in the constructor.

Resolve config repository with type-hint on the constructor

---

README.md
composer.json

This will make the package auto-discoverable.
Also fixes the wrong cashier method name in readme.

Add Laravel 5.5 package auto-discovery support

---

src/Mpociot/VatCalculator/VatCalculator.php
tests/VatCalculatorTest.php

In the Netherlands we have more than one tax rate. 
High: 21% and Low: 6%.
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/internationaal/btw_voor_buitenlandse_ondernemers/btw_berekenen/btw_tarieven/
I've added this functionality to this repository to help Dutch users.

Added functionality for high and low tax types

---

README.md

In the Preconfigured routes section in the Readme.md:
Changes the tax-rate-for-country  to tax-rate-for-location.
Thats how it is defined in the routes.php
`Route::get('vatcalculator/tax-rate-for-location/{country?}/{postal_code?}'`

Fix README.md Preconfigured routes name tax-rate-for-location

---

src/Mpociot/VatCalculator/VatCalculator.php

Guadeloupe, Guyane and Mayotte are french overseas but were referenced as 'ES' (spain) in $postalCodeExceptions instead of 'FR' (They are well referenced in $taxRules var)

Fix code $postalCodeExceptions for french overseas

---

src/Mpociot/VatCalculator/VatCalculator.php

Hi,
users sometimes copy and paste VAT ids from various resources using various formatting. The validation method already removes common separators.
This adds non-breaking space removal which is sometimes used as a number separator. It removes both Unicode and ISO-8859-x representation.
Though it might be handy for other users that's why I'm submitting this PR.
Thank you!

Remove non-breaking spaces from VAT ID

---

src/Mpociot/VatCalculator/VatCalculatorServiceProvider.php

There's every possibility I'm just doing something wrong, but when I resolve an instance of `VatCalulator` from the container it doesn't resolve [the instance we bind in the service provider](https://github.com/mpociot/vat-calculator/blob/master/src/Mpociot/VatCalculator/VatCalculatorServiceProvider.php#L74).
This appears to be because the name we are binding to contains a leading slash;
```
>>> '\Mpociot\VatCalculator\VatCalculator'
=> "\Mpociot\VatCalculator\VatCalculator"
>>> \Mpociot\VatCalculator\VatCalculator::class
=> "Mpociot\VatCalculator\VatCalculator"
```
If it's me and I should be doing something differently, please let me know! Thanks!
Edit: After more digging it seems that binding with leading slashes stopped being supported with Laravel 5.4;
```
Binding classes into the …
```

Bind using VatCalculator::class rather than string

---

composer.json
src/Mpociot/VatCalculator/VatCalculator.php
tests/VatCalculatorTest.php

Probably some of the most ugly code I wrote in the past years but it gets the job done for now 🤷‍♂️ 
Closes https://github.com/driesvints/vat-calculator/issues/113

Validate UK VAT numbers

---

composer.json
src/Mpociot/VatCalculator/VatCalculator.php

Hi,
I just used get_headers to get the status code of the api, because it was throwing an uncatchable 404 error when using file_get_contents and the vat number wasnt a valid one.
Now it should work without the need for the cURL extension aswell.
Thank you
PS: Hope this time, there is no problem...

Using get_headers to avoid 404 status code with file_get_contents

---

src/VatCalculator.php

Postal code for the city of Livigno and Campione d'Italia has been changed in 2018.
[https://en.wikipedia.org/wiki/Livigno](https://en.wikipedia.org/wiki/Livigno)
[https://en.wikipedia.org/wiki/Campione_d%27Italia](https://en.wikipedia.org/wiki/Campione_d%27Italia)
The old postal codes are shared with other cities and for those cities vat should be applied so I've set only the new ones.

Update italy postal code exceptions

---

src/VatCalculator.php

After checking the changes in #137 I've noticed that Campione d'Italia became part of the EU customs territory on 1 Jan 2020.
That means two relevant changes:
- VAT will apply, but the tax rate will remain that of Switzerland:
- https://en.wikipedia.org/w/index.php?title=Campione_d%27Italia&diff=prev&oldid=937493207
- https://www.europeansources.info/record/directive-eu-2019-475-amending-directives-2006-112-ec-and-2008-118-ec-as-regards-the-inclusion-of-the-italian-municipality-of-campione-ditalia-and-the-italian-waters-of-lake-lugano-in-the-c/
- https://www.euronews.com/2020/01/03/tiny-italian-enclave-in-switzerland-transferred-back-to-italy-and-the-eu-s-customs-union
Unfortunately, this package doesn't support high/low rates for exceptions, so I put just the higher one, like in the …

Correct VAT and postal code for Campione d'Italia

---

README.md
config/vat_calculator.php
src/VatCalculator.php
tests/VatCalculatorTest.php

#142
#36
I have added the function `isValidVatNumberFormat` to validate the formating of the VAT number based on [VIES](http://ec.europa.eu/taxation_customs/vies/faqvies.do#item_11). 
Besides that, I have added an option to the config file, to change the `connection_timeout`of the SOAP client. It's called `soap_timeout` in the config file. Its default value is 30 seconds.
Three questions came into my mind:
1. When validating the formate, I have used your code to "clean up" the VAT number: 
`$vatNumber = str_replace([' ', "\xC2\xA0", "\xA0", '-', '.', ','], '', trim($vatNumber));`
The question is. Why should I replace empty space? As it is officially okay to use it, according to VIES. Obviously, we should trim it. But why should we remove the rest? If the patterns do not match the VAT …

Added isValidVatNumberFormat + connection_timeout for the SOAP Client

---

src/VatCalculator.php

Addes 'rates' to each country, using the source  https://eclear.com/knowledge/eu-vat-rates/.
Changed updated rates for Luxembourg

ADDED DETAILED VAT RATES

---

src/VatCalculator.php

Note: merge in 2024
~~Note 2: the change has to be signed by the president yet, I'll update the PR once that's done~~ signed see below
Source for example here
"The basic VAT rate will remain at 21 percent.  The reduced rate will be 12 percent (so far we have two reduced rates: 10 and 15 percent).  There will be zero tax on books."
Originally: "Základní sazba DPH zůstane 21 procent. Snížená sazba bude nově 12 procent (dosud máme dvě snížené sazby: 10 a 15 procent). Na knihy bude nově nulová daň."  https://www.penize.cz/dph/442212-zmeny-dph-prehledne-kompletni-seznam
Another source:
"The consolidation package introduces only two VAT rates, namely 12 and 21 percent." Originally: "Konsolidační balíček zavádí pouze dvě sazby DPH, a to 12 a 21 procent." …

Starting 2024, CZ has just one low rate 12%

---

src/VatCalculator.php

From 1 January 2024, the following current VAT rates apply in Switzerland:
Normal rate: 8,1 %
Reduced rate: 2,6 %
Special rate for accommodation: 3,8 %
Reason for the increase in tax rates:
In the vote of 25 September 2022, the amendment to the AHV Act and the federal decree on the supplementary financing of the AHV were accepted.
https://www.estv.admin.ch/estv/en/home/value-added-tax/vat-rates-switzerland.html

Update Swiss VAT rates for 2024

---

src/VatCalculator.php

"a standard rate of 23% in mainland Portugal, 16% in the Autonomous Region of the Azores" https://eportugal.gov.pt/en/cidadaos-europeus-viajar-viver-e-fazer-negocios-em-portugal/impostos-para-atividades-economicas-em-portugal/imposto-sobre-valor-acrescentado-iva-em-portugal

Update VAT rate for Azores to 16%

---

src/VatCalculator.php

The low rate is 6% and parking rate should be 12% same as intermediate rate.
See https://finance.belgium.be/en/enterprises/vat/vat-obligation/rates-and-calculation/vat-rates#q1

Reduced rate and parking rate corrected for Belgium

---

src/VatCalculator.php
tests/VatCalculatorTest.php

A full postal code for the Azores is `9[5-9]xx-xxx` but the regex never matches this format since it only looks for numbers.
This PR fixes this issue, for both the Azores and Madeira. It makes `9500` trigger the exception, as well as `9500-339`.
I also noticed the current regex allowed `950000000....` (with unlimited digits). It seems to be useless since Portuguese postal codes are only 4 digits before the hyphen, but I kept this behavior in order to avoid an undesirable breaking change. So `95012341234-339` will match too.

Update postal code exceptions for Portugal

---

src/VatCalculator.php

Finland VAT rise to 25.5% on 1 September 2024
https://www.vatcalc.com/finland/finland-increases-vat-to-24-january-2013/

Update Finland rates

---

src/VatCalculator.php

Without this PR, these territories show an incorrect Tax rate of 20% whereas no VAT is applied there.
source: https://fr.wikipedia.org/wiki/Num%C3%A9rotation_des_d%C3%A9partements_fran%C3%A7ais#G%C3%A9n%C3%A9ralit%C3%A9s

Add missing French overseas

---

src/VatCalculator.php

Per https://marosavat.com/estonia-increase-vat-rate-2025/ - this WILL apply from July 1st 2025.
They also mention an increase per January 1st of the accomodations services (9 to 13%) and books (5 to 9%). I am not sure what the low rate refers to here so I left it alone, but anyway this should be changed in another PR if it needs changing, as this is already effective, and this PR should be held until July 1st.

Update Estonia's main VAT rate to 24%

---

src/VatCalculator.php

According to law, certain housing products will remain at 9% from August 01 2025 to August 01 2026 @see https://mfinante.gov.ro/static/10/Mfp/transparenta/proiectLegemasurifiscale_03072025.pdf

Update Romania's main VAT to 21%, low to 11%
